num_classes: &num_classes 81

runtime:
  rank_init: true
  runner:
    type: quant
  task_names: quant_det
quant:
  quant_type: ptq
  deploy_backend: academic
  cali_batch_size: 8 # 256 / 4(bs) / n(gpus) 
  tricks:
    special: [backbone.layer0.0]
    bit: 8
  ptq:
    pattern: layer # layer for ada, block for brecq/qdrop
    scale_lr: 4.0e-5
    warm_up: 0.25
    weight: 0.005
    max_count: 20000
    b_range: [20, 2]
    keep_gpu: false
    round_mode: learned_hard_sigmoid
    prob: 1. # 1. for brecq/ada, 0.5 for qdrop
  prepare_args:
    extra_qconfig_dict:
      w_observer: MSEObserver
      a_observer: EMAMSEObserver
      a_fakequantize: QDropFakeQuantize
      w_fakequantize: AdaRoundFakeQuantize
      w_qscheme:
        bit: 2
        symmetry: false
        per_channel: true
        pot_scale: false
        p: 2.4
      a_qscheme:
        bit: 4
        symmetry: false
        per_channel: false
        pot_scale: false
        p: 2.4
    leaf_module: [Space2Depth, FrozenBatchNorm2d]
    extra_quantizer_dict:
      additional_module_type: [ConvFreezebn2d, ConvFreezebnReLU2d]


flip:
  type: flip
  kwargs:
    flip_p: 0.5

train_resize:
  type: keep_ar_resize
  kwargs:
    scales: [640, 672, 704, 736, 768, 800]
    max_size: 1333
    separate_wh: true

test_resize: &test_resize
  type: keep_ar_resize
  kwargs:
    scales: [800]
    max_size: 1333
    separate_wh: true

fix_output_resize:
  type: fix_output_resize
  kwargs:
    scales: [1024, 1024]
    max_size: 1400

expand:
  type: stitch_expand
  kwargs:
    expand_ratios: 2.0
    expand_prob: 0.5

crop:
  type: crop
  kwargs:
    means: [123.675, 116.280, 103.530]
    scale: 1024
    crop_prob: 0.5

color_jitter:
  type: color_jitter
  kwargs:
    brightness: 32
    contrast: [0.5, 1.5]
    saturation: [0.5, 1.5]
    hue: 18

to_tensor: &to_tensor
  type: to_tensor

normalize: &normalize
  type: normalize
  kwargs:
    mean: [0.485, 0.456, 0.406] # ImageNet pretrained statics
    std: [0.229, 0.224, 0.225]

dataset: # Required.
  train:
    dataset:
      type: coco
      kwargs:
        meta_file: coco/annotations/instances_train2017.json
        image_reader:
          type: fs_opencv
          kwargs:
            image_dir: coco/train2017
            color_mode: RGB
        transformer: [*to_tensor, *normalize]
  test:
    dataset:
      type: coco
      kwargs:
        # meta_file: /mnt/lustre/fanyunqian/united-perception/dep/calibrate.json
        meta_file: coco/annotations/instances_val2017.json
        image_reader:
          type: fs_opencv
          kwargs:
            image_dir: coco/val2017
            color_mode: RGB
        transformer: [*test_resize, *to_tensor, *normalize]
        evaluator:
          type: COCO               # choices = {'COCO', 'VOC', 'MR'}
          kwargs:
            gt_file: coco/annotations/instances_val2017.json
            iou_types: [bbox]
  batch_sampler:
    type: aspect_ratio_group
    kwargs:
      sampler:
        type: dist
        kwargs: {}
      batch_size: 4
      aspect_grouping: [1]
  dataloader:
    type: base
    kwargs:
      num_workers: 4
      alignment: 32
      pin_memory: true


trainer: # Required.
  max_epoch: 6             # total epochs for the training
  test_freq: 1
  save_freq: 1
  optimizer:                 # optimizer = SGD(params,lr=0.001,momentum=0.9,weight_decay=0.0001)
    type: SGD
    kwargs:
      lr: 0.00000625
      momentum: 0.9
      weight_decay: 0.0
  lr_scheduler:              # lr_scheduler = MultStepLR(optimizer, milestones=[9,14],gamma=0.1)
    warmup_epochs: 0        # set to be 0 to disable warmup. When warmup,  target_lr = init_lr * total_batch_size
    warmup_type: linear
    warmup_ratio: 0.001
    type: MultiStepLR
    kwargs:
      milestones: [2, 4]     # epochs to decay lr
      gamma: 0.1             # decay rate

saver: # Required.
  save_dir: checkpoints/det/retinanet/r50/w2a4    # dir to save checkpoints
  resume_model: resume_path
  results_dir: results_dir/det/retinanet/r50/w2a4  # dir to save detection results. i.e., bboxes, masks, keypoints
  auto_resume: false  # find last checkpoint from save_dir and resume from it automatically
                     # this option has the highest priority (auto_resume > opts > resume_model > pretrain_model)


hooks:
- type: auto_checkpoint

net:
- name: backbone                # backbone = resnet50(frozen_layers, out_layers, out_strides)
  type: resnet50
  kwargs:
    frozen_layers: [0, 1]      # layer0...1 is fixed
    out_layers: [2, 3, 4]       # layer1...4, commonly named Conv2...5
    out_strides: [8, 16, 32]    # tell the strides of output features
    normalize:
      type: mqbench_freeze_bn
    initializer:
      method: msra
- name: neck
  prev: backbone
  type: FPN
  kwargs:
    outplanes: 256
    start_level: 3
    num_level: 5                  # if num_level>len(backbone.out_layers), additional conv with be stacked.
    out_strides: [8, 16, 32, 64, 128] # strides of output features. aka., anchor strides for roi_head
    downsample: conv              # method to downsample, for FPN, it's pool, for RetienaNet, it's conv
    upsample: nearest             # method to interp, nearest or bilinear
    initializer:
      method: xavier
- name: roi_head
  prev: neck
  type: RetinaSubNet
  kwargs:
    feat_planes: 256          # channels of intermediate conv
    num_classes: *num_classes
                                        # number of classes including backgroudn. for rpn, it's 2; for RetinaNet, it's 81
    initializer:
      method: normal
      std: 0.01
    init_prior: 0.01
    num_anchors: 9
    class_activation: sigmoid
- name: post_process
  prev: roi_head
  type: retina_post
  kwargs:
    num_classes: *num_classes
                                 # number of classes including backgroudn. for rpn, it's 2; for RetinaNet, it's 81
    cfg:
      cls_loss:
        type: sigmoid_focal_loss
        kwargs:
          num_classes: *num_classes
          alpha: 0.25
          gamma: 2.0
      loc_loss:
        type: l1_loss
      anchor_generator:
        type: hand_craft
        kwargs:
          anchor_ratios: [0.5, 1, 2]  # anchor strides are provided as feature strides by feature extractor
          anchor_scales: [4, 5.0396842, 6.34960421]   # scale of anchors relative to feature map
      roi_supervisor:
        type: retina
        kwargs:
          allowed_border: -1              # >=0 for rpn, -1 for retinanet(keep all anchors)
          matcher:
            type: max_iou
            kwargs:
              positive_iou_thresh: 0.5
              negative_iou_thresh: 0.4
              ignore_iou_thresh: 0.5      # Required if provide ignore_regions
              allow_low_quality_match: true   # an anchor is also positive if it has highest iou with any gt
          sampler:
            type: keep_all
            kwargs: {}
      roi_predictor:
        type: base
        kwargs:
          pre_nms_score_thresh: 0.05    # to reduce computation
          pre_nms_top_n: 1000
          post_nms_top_n: 1000
          roi_min_size: 0                 # minimum scale of a valid roi
          merger:
            type: retina
            kwargs:
              top_n: 100
              nms:
                type: naive
                nms_iou_thresh: 0.5
