num_classes: &num_classes 81
runtime:
  runner:
    type: quant
  aligned: true
  async_norm: true
  special_bn_init: true
  task_names: quant_det
quant:
  quant_type: qat
  deploy_backend: vitis
  cali_batch_size: 50

mosaic:
  type: mosaic
  kwargs:
    extra_input: true
    tar_size: 640
    fill_color: 0

random_perspective:
  type: random_perspective_yolox
  kwargs:
    degrees: 10.0 # 0.0
    translate: 0.1
    scale: [0.5, 1.5] # 0.5
    shear: 2.0 # 0.0
    perspective: 0.0
    fill_color: 0  # 0
    border: [-320, -320]

flip: &flip
  type: flip
  kwargs:
    flip_p: 0.5

to_tensor: &to_tensor
  type: custom_to_tensor

train_resize: &train_resize
  type: keep_ar_resize_max
  kwargs:
    max_size: 320
    padding_type: left_top
    padding_val: 0

test_resize: &test_resize
  type: keep_ar_resize_max
  kwargs:
    max_size: 320
    padding_type: left_top
    padding_val: 0

normalize_inverse:
  type: normalize_inverse

dataset:
  train:
    dataset:
      type: coco
      kwargs:
        meta_file: coco/annotations/instances_train2017.json
        image_reader:
          type: fs_opencv
          kwargs:
            image_dir: coco/train2017
            color_mode: GRAY
        transformer: [*train_resize, *to_tensor]
    batch_sampler:
      type: base
      kwargs:
        sampler:
          type: dist
          kwargs: {}
        batch_size: 8
  test:
    dataset:
      type: coco
      kwargs:
        meta_file: coco/annotations/instances_val2017.json
        image_reader:
          type: fs_opencv
          kwargs:
            image_dir: coco/val2017
            color_mode: GRAY
        transformer: [*test_resize, *to_tensor]
        evaluator:
          type: COCO
          kwargs:
            gt_file: coco/annotations/instances_val2017.json
            iou_types: [bbox]
    batch_sampler:
      type: base
      kwargs:
        sampler:
          type: dist
          kwargs: {}
        batch_size: 8
  dataloader:
    type: base
    kwargs:
      num_workers: 8
      alignment: 32
      worker_init: true
      pad_type: batch_pad

trainer: # Required.
  max_epoch: &max_epoch 5             # total epochs for the training
  save_freq: 1
  test_freq: 1
  optimizer:                 # optimizer = SGD(params,lr=0.01,momentum=0.937,weight_decay=0.0005)
    register_type: qat_weights
    type: Adam
    kwargs:
      lr: 0.00000078125
      weight_decay: 0.0005      # weight_decay = 0.0005 * batch_szie / 64
  lr_scheduler:
    type: MultiStepLR
    kwargs:
      milestones: [1, 3, 5]
      gamma: 0.1

saver:
  save_dir: checkpoints/yolox-fpga-qat
  results_dir: results_dir/yolox-fpga-qat
  resume_model: resume_path
  auto_resume: false

hooks:
- type: yolox_noaug
  kwargs:
    max_epoch: *max_epoch
    transformer: [*flip, *train_resize, *to_tensor]
- type: auto_save_best

ema:
  enable: false
  ema_type: exp
  kwargs:
    decay: 0.9998

net:
- name: backbone
  type: yolox
  kwargs:
    wid_mul: 0.375
    dep_mul: 0.33
    out_layers: [2, 3, 4]
    out_strides: [8, 16, 32]
    normalize:
      type: solo_bn
    act_fn: {type: ReLU}
    use_spp_pool: false
    focus_type: stem_focus
    input_channels: 1
- name: neck
  prev: backbone
  type: YoloxPAFPN
  kwargs:
    depth: 0.33
    out_strides: [8, 16, 32]
    act_fn: {type: ReLU}
- name: roi_head
  prev: neck
  type: YoloXHead
  kwargs:
    num_classes: *num_classes
                                 # number of classes including backgroudn. for rpn, it's 2; for RetinaNet, it's 81
    width: 0.375
    num_point: &dense_points 1
    act_fn: {type: ReLU}
- name: yolox_post
  prev: roi_head
  type: yolox_post
  kwargs:
    num_classes: *num_classes
                                 # number of classes including backgroudn. for rpn, it's 2; for RetinaNet, it's 81
    cfg:
      loc_loss:
        type: iou_loss
        kwargs:
          loss_type: square_iou
          loss_weight: 5.0
      cls_loss:
        type: sigmoid_cross_entropy
      obj_loss:
        type: sigmoid_cross_entropy
      anchor_generator:
        type: fcos   # yolox
        kwargs:
          dense_points: *dense_points
          center: false
      roi_supervisor:
        type: ota
        kwargs:
          num_classes: *num_classes
          matcher:
            type: ota
            kwargs:
              num_classes: *num_classes
      roi_predictor:
        type: yolox
        kwargs:
          num_classes: *num_classes
          pre_nms_score_thresh: 0.01
          nms:
            type: naive
            nms_iou_thresh: 0.65
