mocov1: &mocov1
  type: torch_mocov1
runtime:
  task_names: ssl
dataset: # Required.
  train:
    dataset:
      type: cls
      kwargs:
        meta_file: images/meta/train.txt
        meta_type: moco_imagenet
        image_reader:
          type: fs_pillow
          kwargs:
            image_dir: images/train
            color_mode: RGB
            memcached: true
        transformer: [*mocov1]
    batch_sampler:
      type: base
      kwargs:
        sampler:
          type: dist
          kwargs: {}
        batch_size: 64
    dataloader:
      type: cls_base
      kwargs:
        num_workers: 12
        pin_memory: true

trainer: # Required.
  max_epoch: 200
  test_freq: 500
  save_freq: 5
  is_eval: false
  only_save_latest: true
  optimizer:                 # optimizer = SGD(params,lr=0.001,momentum=0.9,weight_decay=0.0001)
    type: SGD
    kwargs:
      lr: 0.06
      nesterov: true
      momentum: 0.9
      weight_decay: 0.0001
  lr_scheduler:              # lr_scheduler = MultStepLR(optimizer, milestones=[9,14],gamma=0.1)
    warmup_iter: 0          # 1000 iterations of warmup
    warmup_type: linear
    warmup_register_type: no_scale_lr
    warmup_ratio: 0
    type: MultiStepLR
    kwargs:
      milestones: [120, 160]
      gamma: 0.1

saver: # Required.
  save_dir: moco_v1_bs512/checkpoints/cls_std     # dir to save checkpoints
  results_dir: moco_v1_bs512/results_dir/cls_std  # dir to save detection results. i.e., bboxes, masks, keypoints
  auto_resume: true  # find last checkpoint from save_dir and resume from it automatically
                     # this option has the highest priority (auto_resume > opts > resume_model > pretrain_model)

hooks:
- type: auto_save_best

net:
- name: backbone
  type: ssl
  multi_model:
  - name: encoder_q
    type: resnet50
    kwargs:
      frozen_layers: []
      out_layers: [4]         # layer1...4, commonly named Conv2...5
      out_strides: [32]      # tell the strides of output features
      normalize:
        type: solo_bn
      initializer:
        method: msra
  - name: encoder_k
    type: resnet50
    kwargs:
      frozen_layers: []
      out_layers: [4]         # layer1...4, commonly named Conv2...5
      out_strides: [32]      # tell the strides of output features
      normalize:
        type: solo_bn
      initializer:
        method: msra
  wrappers:
  - type: moco
    kwargs:
      dim: 128
      K: 65536

- name: post_process
  type: base_ssl_postprocess
  kwargs:
    ssl_loss:
      type: moco_loss

